apiVersion: apps/v1
kind: Deployment
metadata:
  name: godaddy-ddns
  labels:
    app: godaddy-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: godaddy-ddns
  template:
    metadata:
      labels:
        app: godaddy-ddns
    spec:
      containers:
      - name: godaddy-ddns
        image: dockerregistry.openprint.org:5000/godaddy-ddns:v1
        ports:
        - containerPort: 8950